export default [
  {
    student_id: "190001",
    challenges: 5,
    standard_time: 11,
    subject: "NS_C",
    name: "학생1",
    avg_time: "11",
    avg_error: "0",
  },
  {
    student_id: "190002",
    challenges: 3,
    standard_time: 11,
    subject: "NS_C",
    name: "학생2",
    avg_time: "20",
    avg_error: "3",
  },
  {
    student_id: "190003",
    challenges: 8,
    standard_time: 11,
    subject: "NS_C",
    name: "학생3",
    avg_time: "12",
    avg_error: "1",
  },
  {
    student_id: "190004",
    challenges: 7,
    standard_time: 11,
    subject: "NS_C",
    name: "학생4",
    time: "14",
    avg_error: "1",
  },
  {
    student_id: "190005",
    challenges: 5,
    standard_time: 11,
    subject: "NS_C",
    name: "학생5",
    avg_time: "13",
    avg_error: "1",
  },
  {
    student_id: "190006",
    challenges: 1,
    standard_time: 11,
    subject: "NS_C",
    name: "학생6",
    avg_time: "16",
    avg_error: "2",
  },
  {
    student_id: "190007",
    challenges: 11,
    subject: "NS_C",
    name: "학생7",
    avg_time: "21",
    avg_error: "5",
  },
  {
    student_id: "190008",
    challenges: 2,
    standard_time: 11,
    subject: "NS_C",
    name: "학생8",
    avg_time: "11",
    avg_error: "0",
  },
  {
    student_id: "190009",
    challenges: 3,
    standard_time: 11,
    subject: "NS_C",
    name: "학생9",
    avg_time: "23",
    avg_error: "6",
  },
  {
    student_id: "190010",
    challenges: 2,
    standard_time: 11,
    subject: "NS_C",
    name: "학생10",
    avg_time: "14",
    avg_error: "2",
  },
];
